### ISSUE TITLE
[contract][comment] bug issue after updating contract

### ISSUE THREAD

**Issue by FoodChain1028** [social-tw/social-tw-website#164]
**Describe the bug**
Relay test in branch `feature-contract-comment` now encounters errors in both login and post test.

**To Reproduce**

1. Switch to branch `feature-contract-comment`
2. run `yarn install` && `yarn build`
3. run `yarn relay test`
4. See errors

**Screenshots**
5 errors happen in the test:

```sh
$ yarn workspace @unirep-app/relay run test
$ hardhat test


  LOGIN /login
-----------------------------------------------------------------
Epoch tree depth: 17
State tree depth: 17
History tree depth: 17
Number of epoch keys per epoch: 3
Total fields per user: 6
Sum fields per user: 4
Replacement field nonce bits: 48
Replacement field data bits: 205
-----------------------------------------------------------------
Make sure these match what you expect!
-----------------------------------------------------------------
Deploying EpochKeyVerifier
Deploying ProveReputationVerifier
Deploying UserStateTransitionVerifier
Deploying SignupVerifier
Deploying EpochKeyLiteVerifier
Deploying PreventDoubleActionVerifier
Deploying Unirep
-----------------------------------------------------------------
Bytecode size of Unirep: 16184 bytes
Gas cost of deploying Unirep: 3385237
Deployed to: 0x4D137bb44553d55AE6B28B5391c6f537b06C9cc3
-----------------------------------------------------------------
Deploying EpochKeyVerifier
Deploying EpochKeyVerifierHelper
Deploying EpochKeyLiteVerifier
Deploying EpochKeyLiteVerifierHelper
Unirep app with epoch length 100000 is deployed to 0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1
Starting synchronizer...
Synchronizer started
Starting Helia ipfs node...
Helia ipfs node started
Starting transaction manager...
Transaction manager started
Listening on port 8000
    ✔ /api/login, return url
    ✔ /api/user, init user with wrong code and return error
    ✔ /api/user, init user
    ✔ /api/signup, user sign up with wrong proof and return error (473ms)
    ✔ /api/signup, user sign up with wallet (8736ms)
    1) /api/signup, sign up with the same commitment
    ✔ /api/signup, sign up with different attesterId (3781ms)
    ✔ /api/signup, user sign up with server (11866ms)
    2) /api/signup, handle duplicate signup
    3) /api/login, registered user with own wallet
    4) /api/login, registered user with server wallet

  POST /post
    5) "before each" hook for "should create a post"


  7 passing (52s)
  5 failing
1) LOGIN /login
       /api/signup, sign up with the same commitment:

      AssertionError: expected promise to be rejected with 'Error' but it was fulfilled with ''
      + expected - actual

      +Error
      
  

  2) LOGIN /login
       /api/signup, handle duplicate signup:

      AssertionError: expected Response{ domain: null, …(36), …(1) } to have status code 400 but got 200
      + expected - actual

      -200
      +400
      
      at /Users/foodchain/Documents/PSE/social-tw-website/packages/relay/test/login.test.ts:357:37
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Context.<anonymous> (test/login.test.ts:345:9)

  3) LOGIN /login
       /api/login, registered user with own wallet:

      AssertionError: expected 1 to equal 2
      + expected - actual

      -1
      +2
      
      at Context.<anonymous> (test/login.test.ts:369:42)

  4) LOGIN /login
       /api/login, registered user with server wallet:

      AssertionError: expected 1 to equal 3
      + expected - actual

      -1
      +3
      
      at Context.<anonymous> (test/login.test.ts:378:42)

  5) POST /post
       "before each" hook for "should create a post":

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/post.test.ts:67:29)
```
I reckon this might cause due to the change of Error in smart contract, which were changed by me ( from `require...` to `Customized Errors`). However, since I am not so familiar with the structure in relayer and some of the errors seem like having no relation with the changes in contract, I might need someone who knows the structure of relayer to deal with this.

**Comment by ryanycw** [comment]
I will have a look
